src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 *
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 */
class Property
{
    const HEAT = [
        0 => 'Electric',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min="5", max="255")
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */

    private $discription;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=500)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDiscription(): ?string
    {
        return $this->discription;
    }

    public function setDiscription(?string $discription): self
    {
        $this->discription = $discription;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType():string
    {
      return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('discription')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class,
                [
                    'choices' => $this->getChoices()
                ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices(){
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k =>$v ){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;


use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use App\Service\ServiceTwig;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\services;
use Twig\Environment;



class PropertyController extends AbstractController
{

     private $repository;
     private $em;



     public function __construct(PropertyRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
     }


    /**
     * @Route("/biens", name="propertyIndex")
     * @return Response
     */
    public function index(Request $request,PaginatorInterface $paginator): Response
    {
        /**  $property = new Property();
        $property->setTitle('Mon premierbien')
            ->setPrice(20000)
            ->setRooms(4)
            ->setBedrooms(3)
            ->setDiscription('une petite description')
            ->setSurface(60)
            ->setFloor(4)
            ->setHeat(1)
            ->setCity('Sousse')
            ->setAddress('rue touristique chatt matme')
            ->setPostalCode('4042')
        ;
        $em = $this->getDoctrine()->getManager();
        $em->persist($property);
        $em->flush();

 @var  $repository
 * La premier méthode
        $repository = $this ->getDoctrine() ->getRepository(Property::class);
        dump($repository);
 **/
        //$proprety = $this->repository->findAll();
        //$proprety = $this->repository->findAllVisible();
       // $proprety[0]->setSold(true);
        //$this ->em->flush();

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class,$search);
        $form->handleRequest($request);

        $paginator  = $this->get('knp_paginator');
        $properties = $paginator->paginate(
            $this->repository->findVisibleQuery($search),
            $request->query->getInt('page',1),2
        );
        //partie d la pagination
        //$properties = $this->repository->findAll($request);

        //dump($properties);
        return $this->render( 'property/index.html.twig', [
                'current_menu' => 'properties',
                'properties' => $properties,
                'form' =>$form->createView()
        ]
        );

    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\]*"})
     * @param Property $property
     * @return Response
     */
    public function show(Property $property, string $slug): Response
    {

        if ($property->getSlug() !== $slug){
            $this->redirectToRoute('property.show',[
                'id' =>$property->getId(),
                 'slug' =>$property->getSlug()
            ], 301);
        }
     return $this->render( 'property/show.html.twig', [
         'current_menu' => 'properties',
         'property' => $property]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">{{ property.title }}</a>
        </h5>
        <p class="card-text">{{ property.city }} ({{ property.postalCode }})</p>
        <div>
            <div class="text-primary" style="front-size:2rem; font-weight: bold;">
                {{ property.formattedPrice }}
            </div>
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Tous nos bien' %}
{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{form_start(form)}}
            <div class="form-row">
                <div class="col">
                {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{form_end(form)}}
        </div>
    </div>
    <div class="container mt-4">
        <h1><i>Voir tous nos bien</i></h1>
        <br>
        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                {% include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="pagination">

        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}
{% block body %}
    <div class= "jumbotron">
        <div class="container">
            <div class="row">

                <div class="col-md-8">
                </div>

                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pieces - {{ property.surface }} m² </h2>
                    <div class="text-primary" style="font-size: 3rem;font-weight: bold">{{ property.formattedPrice }} € </div>
                    <a href="#" class="btn btn-primary">Contacter l'agence </a>
                </div>
            </div>


        </div>
    </div>
    <div class="container mt-4">

        <p>
            {{ property.discription | nl2br }}
        </p>


        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Piéces</td>
                        <td>{{ property.rooms }} </td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }} </td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor }} </td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }} </td>
                    </tr>
                </table>
            </div>



            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>

    </div>
{% endblock %}